### ISSUE TITLE
Refactor existing code

### ISSUE THREAD

**Issue by KlavierCat** [Coding-Drunk/bluebank#30]
**TODO**:
- [ ] Naming: currently there are both Id and ID. We need to unify this, both in app.js and the faked DB. Function names can be improved to make more sense
- [ ] add comment, use Javadoc format.
- [ ] Stay DRY: try to abstract away anything that is repetitive in our current code
- [ ] if they are constants, do not use var, use const
- [ ] refactor long function. Functions shouldn't be too long and each function should do only one thing.
- [ ] Reorder: both consts / vars and function. In an order that makes more senses.
- [ ] If necessary, separate the code into different modules and use "require" to require them. Probably not necessary at this stage.
